apiVersion: batch/v1
kind: Job
metadata:
  name: medical-3d-seg-brats
  namespace: "your namespace"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: medical-3d-seg-brats
          image: "you docker image position"
          stdin: true
          tty: true
          args:
            [
              "python", "Code/UnetBRATS/main.py", 
              "--learning_rate=5e-2", "--max_iterations=30000", "--unsup_weight=1.0", "--spatial_weight=0.25", "--hyp=0.05",
              "--pvc"
            ]
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 32Gi
              cpu: 5000m
            requests:
              memory: 32Gi
              cpu: 5000m
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/credentials.json
          volumeMounts:
            - name: gcp-credentials
              mountPath: /etc/gcp
              readOnly: true
            - name: dataset-volume
              mountPath: /pvc
            - mountPath: /dev/shm
              name: shared-memory-hack
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp
            items:
              - key: data-manager
                path: credentials.json
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: brats-dataset
        - name: shared-memory-hack
          emptyDir:
            medium: Memory

